### ISSUE TITLE
Repository is incompatible with WoWUp

### ISSUE THREAD

**Issue by KevinTyrrell** [Finalfantasiser/FinalArenaCalculator#1]
Installing FinalArenaCalculator for TBC using WoWUp by inputting the URL of this repository yields the following error:

![image](https://user-images.githubusercontent.com/12791400/170363584-3a55abbc-09d7-4b14-9296-0d9021144512.png)

The URL used for installing for the above image was: https://github.com/Finalfantasiser/FinalArenaCalculator

In order for WoWUp to recognize this repository, you must create a [Release](https://github.com/Finalfantasiser/FinalArenaCalculator/releases) that includes a `.zip` file whose file name ends with `-bcc`. For example the zip file may be called `FinalArenaCalculatorv1.0.0-bcc.zip`

Given the popularity of WoWUp and the lack of Curseforge as an option, it is highly recommended you make this repository compatible with WoWUp in order to allow ease-of-use when installing.

**Comment by Finalfantasiser** [comment]
Thanks! I was trying to figure it out :D
Resolved.
